from distutils.cmd import Command
from typing import ClassVar, List, Optional, Tuple

class bdist_wininst(Command):
    description: ClassVar[str] = ...
    user_options: ClassVar[List[Tuple[str, Optional[str], str]]] = ...
    boolean_options: ClassVar[List[str]] = ...

    bdist_dir: Optional[str]
    plat_name: Optional[str]
    keep_temp: int
    no_target_compile: int
    no_target_optimize: int
    target_version: Optional[str]
    dist_dir: Optional[str]
    bitmap: Optional[str]
    title: Optional[str]
    skip_build: Optional[str]
    install_script: Optional[str]
    pre_install_script: Optional[str]
    user_access_control: Optional[str]
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    def get_inidata(self) -> str: ...
    def create_exe(self, arcname: str, fullname: str, bitmap: Optional[str] = ...) -> None: ...
    def get_installer_filename(self, fullname: str) -> str: ...
    def get_exe_bytes(self) -> bytes: ...
