import sys
from distutils.cmd import Command
from msilib import Database, Dialog
from typing import Any, ClassVar, List, Optional, Tuple

assert sys.platform == "win32"

class PyDialog(Dialog):
    def __init__(self, *args: Any, **kw: Any) -> None: ...
    def title(self, title: str) -> None: ...
    def back(self, title: str, next: Any, name: str = ..., active: int = ...): ...
    def cancel(self, title: str, next: Any, name: str = ..., active: int = ...): ...
    def next(self, title: str, next: Any, name: str = ..., active: int = ...): ...
    def xbutton(self, name: str, title: str, next: Any, xpos: float): ...

class bdist_msi(Command):
    description: ClassVar[str]
    user_options: ClassVar[List[Tuple[str, Optional[str], str]]]
    boolean_options: ClassVar[List[str]]
    all_versions: ClassVar[List[str]]
    other_version: ClassVar[str]

    bdist_dir: Optional[str]
    plat_name: Optional[str]
    keep_temp: int
    no_target_compile: int
    no_target_optimize: int
    target_version: Optional[str]
    dist_dir: Optional[str]
    skip_build: Optional[int]
    install_script: Optional[str]
    pre_install_script: Optional[str]
    versions: List[str]
    install_script_key: Optional[str]

    db: Optional[Database]
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    def add_files(self) -> None: ...
    def add_find_python(self) -> None: ...
    def add_scripts(self) -> None: ...
    def add_ui(self) -> None: ...
    def get_installer_filename(self, fullname: str): ...
