from distutils.cmd import Command
from typing import IO, Any, ClassVar, List, Optional, Tuple

from docutils.utils import Reporter

class SilentReporter(Reporter):
    messages: Any = ...
    def __init__(
        self,
        source: Any,
        report_level: Any,
        halt_level: Any,
        stream: Optional[IO] = ...,
        debug: int = ...,
        encoding: str = ...,
        error_handler: str = ...,
    ) -> None: ...
    def system_message(self, level: Any, message: Any, *children: Any, **kwargs: Any): ...

HAS_DOCUTILS: bool

class check(Command):
    description: ClassVar[str]
    user_options: ClassVar[List[Tuple[str, Optional[str], str]]]
    boolean_options: ClassVar[List[str]]

    restructuredtext: int = ...
    metadata: int = ...
    strict: int = ...
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def warn(self, msg: str): ...
    def run(self) -> None: ...
    def check_metadata(self) -> None: ...
    def check_restructuredtext(self) -> None: ...
