from distutils.cmd import Command
from typing import Any, ClassVar, List, Optional, Set, Tuple

PYTHON_SOURCE_EXTENSION: str

class install_lib(Command):
    description: ClassVar[str]
    user_options: ClassVar[List[Tuple[str, Optional[str], str]]]
    boolean_options: ClassVar[List[str]]
    negative_opt: ClassVar[Set[str]]

    install_dir: Optional[str]
    build_dir: Optional[str]
    force: int
    compile: Optional[int]
    optimize: Optional[str]
    skip_build: Optional[int]

    multiarch: Any = ...
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    def build(self) -> None: ...
    def install(self) -> Optional[List[str]]: ...
    def byte_compile(self, files: Any) -> None: ...
    def get_outputs(self) -> List[str]: ...
    def get_inputs(self) -> List[str]: ...
