from distutils.cmd import Command
from typing import Any, ClassVar, List, Optional, Tuple

class install_egg_info(Command):
    description: ClassVar[str]
    user_options: ClassVar[List[Tuple[str, Optional[str], str]]]

    install_dir: Optional[str]
    install_layout: Optional[str]
    prefix_option: Any = ...

    target: str
    outputs: List[str]
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    def get_outputs(self) -> List[str]: ...

def safe_name(name: Any): ...
def safe_version(version: Any): ...
def to_filename(name: Any): ...
