from distutils.cmd import Command
from distutils.core import PyPIRCCommand
from typing import Callable, ClassVar, Dict, List, Optional, Tuple
from urllib.request import HTTPPasswordMgr

class register(PyPIRCCommand):
    description: ClassVar[str]
    user_options: ClassVar[List[Tuple[str, Optional[str], str]]]
    boolean_options: ClassVar[List[str]]
    sub_commands: ClassVar[List[Tuple[str, Optional[Callable[[Command], bool]]]]]

    list_classifiers: int = ...
    strict: int = ...
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    def check_metadata(self) -> None: ...
    def classifiers(self) -> None: ...
    def verify_metadata(self) -> None: ...
    def send_metadata(self) -> None: ...
    def build_post_data(self, action: str) -> Dict[str, str]: ...
    def post_to_server(self, data: Dict[str, str], auth: Optional[HTTPPasswordMgr] = ...): ...
