from distutils.config import PyPIRCCommand
from typing import ClassVar, List, Optional, Tuple

class upload(PyPIRCCommand):
    description: ClassVar[str]
    user_options: ClassVar[List[Tuple[str, Optional[str], str]]]
    boolean_options: ClassVar[List[str]]

    username: str = ...
    password: str = ...
    show_response: int = ...
    sign: bool = ...
    identity: Optional[str]

    repository: Optional[str]
    realm: Optional[str]
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    def upload_file(self, command: str, pyversion: str, filename: str) -> None: ...
