from distutils import log as log
from distutils.core import Command as Command
from distutils.dir_util import remove_tree as remove_tree
from typing import List, Optional, Tuple

class clean(Command):
    description: str = ...
    user_options: List[Tuple[str, Optional[str], str]] = ...
    boolean_options: List[str] = ...
    build_base: Optional[str] = ...
    build_lib: Optional[str] = ...
    build_temp: Optional[str] = ...
    build_scripts: Optional[str] = ...
    bdist_base: Optional[str] = ...
    all: Optional[bool] = ...
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
